version: '3.4'

networks:
  backend:

services:
  customerdb:
    container_name: customer-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - backend
    ports:
      - 8001:1433

  customerwebapi:
    container_name: customer-api
    image: ${DOCKER_REGISTRY-}customerwebapi
    build: Microservices/CustomerWebApi
    networks:
      - backend
    ports:
      - 8002:80
    environment:
      - DB_HOST=customerdb
      - DB_NAME=customer
      - DB_PASSWORD=password@12345#
      - DB_USERID=sa

  productdb:
    container_name: product-db
    image: mysql:8.0.32-oracle
    environment:
      - MYSQL_ROOT_PASSWORD=password@12345#
    networks:
      - backend
    ports:
      - 8003:3306

  productwebapi:
    container_name: product-api
    image: ${DOCKER_REGISTRY-}productwebapi
    build: Microservices/ProductWebApi
    networks:
      - backend
    ports:
      - 8004:80
    environment:
      - DB_HOST=productdb
      - DB_NAME=product
      - DB_PASSWORD=password@12345#
      - DB_USERID=root